title: Rachmat Hidayat
# logo: /Asset/Foto.jpg
description: text below image
email: your-email@domain.com
twitter_username: jekyllrb
github_username:  jekyll
#show_downloads: true
theme: jekyll-theme-minimal
